AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  Max: 70

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30